"""Seed instrument reference data for local development."""

from datetime import date
from decimal import Decimal
from uuid import uuid4

from app.modules.security_master.models import EquityExtensionRecord, InstrumentRecord
from app.shared.types import AssetClass

# Each entry contains instrument fields + an optional "shares_outstanding"
# that seeds the equity_extensions table.
SEED_INSTRUMENTS: list[dict[str, object]] = [
    # --- US Technology ---
    {
        "name": "Apple Inc.",
        "ticker": "AAPL",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NASDAQ",
        "country": "US",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "shares_outstanding": Decimal("15_000_000_000"),
        "listed_date": date(1980, 12, 12),
    },
    {
        "name": "Microsoft Corporation",
        "ticker": "MSFT",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NASDAQ",
        "country": "US",
        "sector": "Technology",
        "industry": "Software",
        "shares_outstanding": Decimal("7_400_000_000"),
        "listed_date": date(1986, 3, 13),
    },
    {
        "name": "Alphabet Inc.",
        "ticker": "GOOGL",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NASDAQ",
        "country": "US",
        "sector": "Technology",
        "industry": "Internet Services",
        "shares_outstanding": Decimal("12_200_000_000"),
        "listed_date": date(2004, 8, 19),
    },
    {
        "name": "NVIDIA Corporation",
        "ticker": "NVDA",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NASDAQ",
        "country": "US",
        "sector": "Technology",
        "industry": "Semiconductors",
        "shares_outstanding": Decimal("24_600_000_000"),
        "listed_date": date(1999, 1, 22),
    },
    # --- US Consumer Discretionary ---
    {
        "name": "Amazon.com Inc.",
        "ticker": "AMZN",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NASDAQ",
        "country": "US",
        "sector": "Consumer Discretionary",
        "industry": "E-Commerce",
        "shares_outstanding": Decimal("10_300_000_000"),
        "listed_date": date(1997, 5, 15),
    },
    {
        "name": "Tesla Inc.",
        "ticker": "TSLA",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NASDAQ",
        "country": "US",
        "sector": "Consumer Discretionary",
        "industry": "Automobiles",
        "shares_outstanding": Decimal("3_200_000_000"),
        "listed_date": date(2010, 6, 29),
    },
    # --- US Financials ---
    {
        "name": "JPMorgan Chase & Co.",
        "ticker": "JPM",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Financials",
        "industry": "Banking",
        "shares_outstanding": Decimal("2_900_000_000"),
        "listed_date": date(1969, 3, 5),
    },
    {
        "name": "Goldman Sachs Group Inc.",
        "ticker": "GS",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Financials",
        "industry": "Investment Banking",
        "shares_outstanding": Decimal("340_000_000"),
        "listed_date": date(1999, 5, 4),
    },
    # --- US Healthcare ---
    {
        "name": "Johnson & Johnson",
        "ticker": "JNJ",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "shares_outstanding": Decimal("2_400_000_000"),
        "listed_date": date(1944, 9, 25),
    },
    {
        "name": "UnitedHealth Group Inc.",
        "ticker": "UNH",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Healthcare",
        "industry": "Managed Healthcare",
        "shares_outstanding": Decimal("920_000_000"),
        "listed_date": date(1984, 10, 17),
    },
    # --- US Energy ---
    {
        "name": "Exxon Mobil Corporation",
        "ticker": "XOM",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "shares_outstanding": Decimal("4_200_000_000"),
        "listed_date": date(1920, 1, 1),
    },
    # --- UK ---
    {
        "name": "AstraZeneca PLC",
        "ticker": "AZN",
        "asset_class": AssetClass.EQUITY,
        "currency": "GBP",
        "exchange": "LSE",
        "country": "GB",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "shares_outstanding": Decimal("1_560_000_000"),
        "listed_date": date(1999, 4, 6),
    },
    {
        "name": "HSBC Holdings PLC",
        "ticker": "HSBA",
        "asset_class": AssetClass.EQUITY,
        "currency": "GBP",
        "exchange": "LSE",
        "country": "GB",
        "sector": "Financials",
        "industry": "Banking",
        "shares_outstanding": Decimal("19_700_000_000"),
        "listed_date": date(1991, 7, 12),
    },
    {
        "name": "Shell PLC",
        "ticker": "SHEL",
        "asset_class": AssetClass.EQUITY,
        "currency": "GBP",
        "exchange": "LSE",
        "country": "GB",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "shares_outstanding": Decimal("6_800_000_000"),
        "listed_date": date(2005, 7, 20),
    },
    {
        "name": "Unilever PLC",
        "ticker": "ULVR",
        "asset_class": AssetClass.EQUITY,
        "currency": "GBP",
        "exchange": "LSE",
        "country": "GB",
        "sector": "Consumer Staples",
        "industry": "Personal Products",
        "shares_outstanding": Decimal("2_500_000_000"),
        "listed_date": date(1929, 1, 1),
    },
    # --- Germany ---
    {
        "name": "SAP SE",
        "ticker": "SAP",
        "asset_class": AssetClass.EQUITY,
        "currency": "EUR",
        "exchange": "XETRA",
        "country": "DE",
        "sector": "Technology",
        "industry": "Enterprise Software",
        "shares_outstanding": Decimal("1_220_000_000"),
        "listed_date": date(1988, 11, 4),
    },
    {
        "name": "Siemens AG",
        "ticker": "SIE",
        "asset_class": AssetClass.EQUITY,
        "currency": "EUR",
        "exchange": "XETRA",
        "country": "DE",
        "sector": "Industrials",
        "industry": "Industrial Conglomerates",
        "shares_outstanding": Decimal("800_000_000"),
        "listed_date": date(1897, 1, 1),
    },
    # --- France ---
    {
        "name": "LVMH Moët Hennessy",
        "ticker": "MC",
        "asset_class": AssetClass.EQUITY,
        "currency": "EUR",
        "exchange": "EURONEXT",
        "country": "FR",
        "sector": "Consumer Discretionary",
        "industry": "Luxury Goods",
        "shares_outstanding": Decimal("502_000_000"),
        "listed_date": date(1987, 6, 1),
    },
    {
        "name": "TotalEnergies SE",
        "ticker": "TTE",
        "asset_class": AssetClass.EQUITY,
        "currency": "EUR",
        "exchange": "EURONEXT",
        "country": "FR",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "shares_outstanding": Decimal("2_350_000_000"),
        "listed_date": date(1929, 3, 28),
    },
    # --- Japan ---
    {
        "name": "Toyota Motor Corporation",
        "ticker": "7203",
        "asset_class": AssetClass.EQUITY,
        "currency": "JPY",
        "exchange": "TSE",
        "country": "JP",
        "sector": "Consumer Discretionary",
        "industry": "Automobiles",
        "shares_outstanding": Decimal("13_370_000_000"),
        "listed_date": date(1949, 5, 16),
    },
    {
        "name": "Sony Group Corporation",
        "ticker": "6758",
        "asset_class": AssetClass.EQUITY,
        "currency": "JPY",
        "exchange": "TSE",
        "country": "JP",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "shares_outstanding": Decimal("1_240_000_000"),
        "listed_date": date(1958, 12, 1),
    },
    # --- Switzerland ---
    {
        "name": "Nestlé S.A.",
        "ticker": "NESN",
        "asset_class": AssetClass.EQUITY,
        "currency": "CHF",
        "exchange": "SIX",
        "country": "CH",
        "sector": "Consumer Staples",
        "industry": "Food Products",
        "shares_outstanding": Decimal("2_700_000_000"),
        "listed_date": date(1905, 1, 1),
    },
    {
        "name": "Novartis AG",
        "ticker": "NOVN",
        "asset_class": AssetClass.EQUITY,
        "currency": "CHF",
        "exchange": "SIX",
        "country": "CH",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "shares_outstanding": Decimal("2_040_000_000"),
        "listed_date": date(1996, 12, 20),
    },
    # --- South Korea ---
    {
        "name": "Samsung Electronics Co.",
        "ticker": "005930",
        "asset_class": AssetClass.EQUITY,
        "currency": "KRW",
        "exchange": "KRX",
        "country": "KR",
        "sector": "Technology",
        "industry": "Semiconductors",
        "shares_outstanding": Decimal("5_970_000_000"),
        "listed_date": date(1975, 6, 11),
    },
    # --- Australia ---
    {
        "name": "BHP Group Limited",
        "ticker": "BHP",
        "asset_class": AssetClass.EQUITY,
        "currency": "AUD",
        "exchange": "ASX",
        "country": "AU",
        "sector": "Materials",
        "industry": "Mining",
        "shares_outstanding": Decimal("5_060_000_000"),
        "listed_date": date(1885, 8, 13),
    },
    # --- Canada ---
    {
        "name": "Royal Bank of Canada",
        "ticker": "RY",
        "asset_class": AssetClass.EQUITY,
        "currency": "CAD",
        "exchange": "TSX",
        "country": "CA",
        "sector": "Financials",
        "industry": "Banking",
        "shares_outstanding": Decimal("1_410_000_000"),
        "listed_date": date(1869, 1, 1),
    },
    # --- Additional US ---
    {
        "name": "Meta Platforms Inc.",
        "ticker": "META",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NASDAQ",
        "country": "US",
        "sector": "Technology",
        "industry": "Social Media",
        "shares_outstanding": Decimal("2_560_000_000"),
        "listed_date": date(2012, 5, 18),
    },
    {
        "name": "Berkshire Hathaway Inc.",
        "ticker": "BRK.B",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Financials",
        "industry": "Diversified Holdings",
        "shares_outstanding": Decimal("2_170_000_000"),
        "listed_date": date(1996, 5, 9),
    },
    {
        "name": "Visa Inc.",
        "ticker": "V",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Financials",
        "industry": "Payment Processing",
        "shares_outstanding": Decimal("2_050_000_000"),
        "listed_date": date(2008, 3, 19),
    },
    {
        "name": "Procter & Gamble Co.",
        "ticker": "PG",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Consumer Staples",
        "industry": "Household Products",
        "shares_outstanding": Decimal("2_360_000_000"),
        "listed_date": date(1890, 1, 1),
    },
    {
        "name": "Chevron Corporation",
        "ticker": "CVX",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "shares_outstanding": Decimal("1_880_000_000"),
        "listed_date": date(1921, 6, 25),
    },
    {
        "name": "Pfizer Inc.",
        "ticker": "PFE",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "shares_outstanding": Decimal("5_640_000_000"),
        "listed_date": date(1944, 1, 1),
    },
    {
        "name": "Walt Disney Company",
        "ticker": "DIS",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Consumer Discretionary",
        "industry": "Entertainment",
        "shares_outstanding": Decimal("1_830_000_000"),
        "listed_date": date(1957, 11, 12),
    },
    {
        "name": "Coca-Cola Company",
        "ticker": "KO",
        "asset_class": AssetClass.EQUITY,
        "currency": "USD",
        "exchange": "NYSE",
        "country": "US",
        "sector": "Consumer Staples",
        "industry": "Beverages",
        "shares_outstanding": Decimal("4_320_000_000"),
        "listed_date": date(1919, 9, 5),
    },
    # --- Additional Europe ---
    {
        "name": "ASML Holding NV",
        "ticker": "ASML",
        "asset_class": AssetClass.EQUITY,
        "currency": "EUR",
        "exchange": "EURONEXT",
        "country": "NL",
        "sector": "Technology",
        "industry": "Semiconductors",
        "shares_outstanding": Decimal("394_000_000"),
        "listed_date": date(1995, 3, 14),
    },
    {
        "name": "Novo Nordisk A/S",
        "ticker": "NOVO.B",
        "asset_class": AssetClass.EQUITY,
        "currency": "DKK",
        "exchange": "CPH",
        "country": "DK",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "shares_outstanding": Decimal("4_480_000_000"),
        "listed_date": date(1981, 1, 1),
    },
    {
        "name": "Roche Holding AG",
        "ticker": "ROG",
        "asset_class": AssetClass.EQUITY,
        "currency": "CHF",
        "exchange": "SIX",
        "country": "CH",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "shares_outstanding": Decimal("680_000_000"),
        "listed_date": date(1920, 4, 19),
    },
    # --- Additional UK ---
    {
        "name": "Rio Tinto PLC",
        "ticker": "RIO",
        "asset_class": AssetClass.EQUITY,
        "currency": "GBP",
        "exchange": "LSE",
        "country": "GB",
        "sector": "Materials",
        "industry": "Mining",
        "shares_outstanding": Decimal("1_630_000_000"),
        "listed_date": date(1962, 1, 1),
    },
    {
        "name": "BP PLC",
        "ticker": "BP",
        "asset_class": AssetClass.EQUITY,
        "currency": "GBP",
        "exchange": "LSE",
        "country": "GB",
        "sector": "Energy",
        "industry": "Oil & Gas",
        "shares_outstanding": Decimal("19_200_000_000"),
        "listed_date": date(1954, 1, 1),
    },
    # --- Additional Asia ---
    {
        "name": "Taiwan Semiconductor Manufacturing",
        "ticker": "2330",
        "asset_class": AssetClass.EQUITY,
        "currency": "TWD",
        "exchange": "TWSE",
        "country": "TW",
        "sector": "Technology",
        "industry": "Semiconductors",
        "shares_outstanding": Decimal("25_930_000_000"),
        "listed_date": date(1994, 9, 5),
    },
    {
        "name": "Alibaba Group Holding",
        "ticker": "9988",
        "asset_class": AssetClass.EQUITY,
        "currency": "HKD",
        "exchange": "HKEX",
        "country": "CN",
        "sector": "Technology",
        "industry": "E-Commerce",
        "shares_outstanding": Decimal("20_330_000_000"),
        "listed_date": date(2019, 11, 26),
    },
    # --- Additional Americas ---
    {
        "name": "Vale S.A.",
        "ticker": "VALE3",
        "asset_class": AssetClass.EQUITY,
        "currency": "BRL",
        "exchange": "B3",
        "country": "BR",
        "sector": "Materials",
        "industry": "Mining",
        "shares_outstanding": Decimal("4_390_000_000"),
        "listed_date": date(1942, 6, 1),
    },
]

# Fields that belong on equity_extensions, not on the base instrument.
_EQUITY_EXTENSION_FIELDS = {"shares_outstanding"}


def build_seed_records() -> tuple[list[InstrumentRecord], list[EquityExtensionRecord]]:
    """Return (instruments, equity_extensions) seed records."""
    instruments: list[InstrumentRecord] = []
    extensions: list[EquityExtensionRecord] = []

    for data in SEED_INSTRUMENTS:
        instrument_id = str(uuid4())

        # Split extension fields from base instrument fields
        ext_data = {k: data[k] for k in _EQUITY_EXTENSION_FIELDS if k in data}
        instr_data = {k: v for k, v in data.items() if k not in _EQUITY_EXTENSION_FIELDS}

        instruments.append(InstrumentRecord(id=instrument_id, **instr_data))

        if ext_data:
            extensions.append(EquityExtensionRecord(instrument_id=instrument_id, **ext_data))

    return instruments, extensions
